@startuml
'https://plantuml.com/use-case-diagram
Student ---> (登录)
Admin --->(登录)
Admin ---> (修改密码)
Student ---> (修改密码)
Student ---> (基本信息)
Student ---> (个人简介)
Admin ---> (基本信息)
Admin ---> (入学前信息)
Student ---> (入学前信息)
Admin ---> (家庭信息)
Student ---> (家庭信息)
Admin ---> (社会关系)
Student ---> (社会关系)
Admin ---> (课程管理)
Admin ---> (选课管理)
Admin ---> (出勤管理)
Admin ---> (作业管理)
Admin ---> (成绩管理)
Student ---> (课程管理)
Student ---> (选课管理)
Student ---> (出勤管理)
Student ---> (作业管理)
Student ---> (成绩管理)
Admin ---> (社会实践)
Admin ---> (科技成果)
Admin ---> (培训讲座)
Admin ---> (校外实训)
Admin ---> (荣誉奖励)
Admin ---> (日常活动)
Admin ---> (请假管理)
Student ---> (社会实践)
Student ---> (科技成果)
Student ---> (培训讲座)
Student ---> (校外实训)
Student ---> (荣誉奖励)
Student ---> (日常活动)
Student ---> (请假管理)
Student ---> (个人消费)
Admin ---> (学生统计)
Admin ---> (分类统计)
Admin ---> (退出)
Student ---> (退出)

@enduml